geonames:
  baseURL: http://download.geonames.org/export/dump/
  zipBaseURL: http://download.geonames.org/export/zip/
  zipFile: allCountries.zip
  admin1File: admin1CodesASCII.txt
  admin2File: admin2Codes.txt
  countryFile: countryInfo.txt
  hierarchyFile: hierarchy.zip
  mainFile: CN.zip
  cityFClass: P
download:
  folder: download
  zipFolder: download/zip
algolia:
  appId: XXX
  appSecret: XXX
  indexName: cities