[geonames]
admin1 = "http://download.geonames.org/export/dump/admin1CodesASCII.txt"
admin2 = "http://download.geonames.org/export/dump/admin2Codes.txt"
country = "http://download.geonames.org/export/dump/countryInfo.txt"